# [sklearn](https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions)

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [2]:
X = np.arange(6).reshape(3, 2)

In [3]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
poly = PolynomialFeatures(degree=2)

In [11]:
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

# from [ x<sub>1</sub>, x<sub>2</sub>] to [1,  x<sub>1</sub>, x<sub>2</sub>, x<sub>1</sub><sup>2</sup>, x<sub>1</sub>x<sub>2</sub>, x<sub>2</sub><sup>2</sup>]

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
from sklearn.pipeline import Pipeline

In [16]:
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                ('linear', LinearRegression(fit_intercept=False))])

In [17]:
x = np.arange(5)

In [18]:
y = 3 - 2 * x + x ** 2 - x ** 3

In [19]:
y

array([  3,   1,  -5, -21, -53])

In [20]:
model = model.fit(x[:, np.newaxis], y)

In [21]:
model.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])

In [22]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [26]:
X[:, 0]

array([0, 0, 1, 1])

In [27]:
X[:, 1]

array([0, 1, 0, 1])

In [23]:
y = X[:, 0] ^ X[:, 1]

In [24]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [25]:
y

array([0, 1, 1, 0], dtype=int32)

In [28]:
X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)

In [33]:
X

array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [30]:
from sklearn.linear_model import Perceptron
clf = Perceptron(fit_intercept=False, max_iter=10, tol=None,
                  shuffle=False).fit(X, y)

In [31]:
clf.predict(X)

array([0, 1, 1, 0], dtype=int32)

In [32]:
clf.score(X, y)

1.0

In [34]:
X = np.array([[1,2],[4,5],[7,8],[10,11]])

In [38]:
X

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [39]:
X[:,0]

array([ 1,  4,  7, 10])

In [40]:
X[:,1]

array([ 2,  5,  8, 11])

In [41]:
y = X[:,0] ** X[:,1]

In [42]:
y

array([         1,       1024,    5764801, 1215752192], dtype=int32)

# ***Note ! in python ** is power, ^ is bitwise XOR***

In [62]:
X = np.array([[1,2,3,4,5],
             [2,3,4,5,3],
             [3,2,5,4,1],
             [2,4,5,3,1],
             [6,7,3,5,1]])

In [63]:
X

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 3],
       [3, 2, 5, 4, 1],
       [2, 4, 5, 3, 1],
       [6, 7, 3, 5, 1]])

In [64]:
X[:,0]

array([1, 2, 3, 2, 6])

In [65]:
y = X[:,0] * 1 + X[:,1] * 2 + X[:,2] * (3**2) + X[:,3]*(4**3) + X[:,4]*(5**4)

In [66]:
y

array([3413, 2239,  933,  872,  992])

In [67]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [68]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [69]:
model.fit(X_train,y_train)

LinearRegression()

In [70]:
model.score(X_train,y_train)

1.0

In [71]:
model.predict(X_test)

array([1429.64485981, 2859.90654206])

In [72]:
model.score(X_test,y_test)

0.8203146169357666

In [73]:
import pandas as pd
data = pd.read_csv("../data/Life Expectancy Data.csv")

In [87]:
data = data.dropna()

In [88]:
len(data.columns)

22

In [89]:
features = list(data.columns[4:])

In [90]:
features

['Adult Mortality',
 'infant deaths',
 'Alcohol',
 'percentage expenditure',
 'Hepatitis B',
 'Measles ',
 ' BMI ',
 'under-five deaths ',
 'Polio',
 'Total expenditure',
 'Diphtheria ',
 ' HIV/AIDS',
 'GDP',
 'Population',
 ' thinness  1-19 years',
 ' thinness 5-9 years',
 'Income composition of resources',
 'Schooling']

In [91]:
X = data.loc[:,features]

In [92]:
y = data.iloc[:,3].values

In [93]:
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [107]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [108]:
model.fit(X_train,y_train)

LinearRegression()

In [109]:
model.score(X_train,y_train)

0.837173993915437

In [112]:
from sklearn.metrics import mean_squared_error

prediction = model.predict(X_test)

In [113]:
mean_squared_error(y_test,prediction)

12.354203912786476