In [1]:
import numpy as np
from scipy import linalg as lina

In [4]:
A = np.random.randint(1,100,(3,3))

In [5]:
A

array([[55, 12, 11],
       [63, 77, 97],
       [ 2,  5, 24]])

In [9]:
b = [[np.random.randint(1,100,1)],[np.random.randint(1,100,1)],[np.random.randint(1,100,1)]]

In [10]:
b

[[array([23])], [array([36])], [array([76])]]

# find inverse matrix of A

In [11]:
lina.inv(A)

array([[ 0.0223736 , -0.00382469,  0.00520355],
       [-0.02163493,  0.02130663, -0.07619829],
       [ 0.00264281, -0.00412016,  0.05710768]])

# Solve linear equation systems

In [13]:
lina.solve(A,b)

array([[[ 0.7723736 ]],

       [[-5.52163493]],

       [[ 4.25264281]]])

# find the determinent

In [14]:
lina.det(A)

60920.0

# find eigen vectors and eigen values

In [19]:
values, vectors = lina.eig(A)

In [20]:
for i in values:
    print(i)

(101.3473939476292+0j)
(39.39386421033202+0j)
(15.258741842038837+0j)


In [21]:
for v in vectors:
    print(v)

[-0.26537333 -0.6670471   0.13388228]
[-0.96167156  0.72968855 -0.87310716]
[-0.06902759  0.15034227  0.46878506]


# test 

In [33]:
M = np.array([[0.8,0.3],[0.2,0.7]])

In [34]:
M

array([[0.8, 0.3],
       [0.2, 0.7]])

In [35]:
values, vectors = lina.eig(M)

In [36]:
for  i in values:
    print(i)

(1+0j)
(0.5+0j)


In [37]:
for j in vectors:
    print(j)

[ 0.83205029 -0.70710678]
[0.5547002  0.70710678]


In [38]:
M2 = np.array([[0.5,0.5],[0.5,0.5]])

In [42]:
values, vectors = np.linalg.eig(M2)

In [43]:
print(values)

[1.00000000e+00 1.11022302e-16]


In [44]:
print(vectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [45]:
M = np.array([[0,1],[1,0]])

In [46]:
s,t = lina.eig(M)

In [47]:
print(s)

[ 1.+0.j -1.+0.j]


In [49]:
for i in t:
    print(i)

[ 0.70710678 -0.70710678]
[0.70710678 0.70710678]
