In [1]:
import numpy as np, pandas as pd
print(pd.__version__,"\n",np.__version__)

1.4.4 
 1.21.5


In [2]:
# Series data 

# see series as a dictionary
data = pd.Series([1,2,3,44,5,7,9,0], index = ["a","b","c","d","e","f","g","h"])
print(data)

print("\n",data["c"], "\n")

print("\n","b" in data, "\n")

print("\n",data.keys(), "\n")
print("\n",list(data.items()), "\n")

a     1
b     2
c     3
d    44
e     5
f     7
g     9
h     0
dtype: int64

 3 


 True 


 Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object') 


 [('a', 1), ('b', 2), ('c', 3), ('d', 44), ('e', 5), ('f', 7), ('g', 9), ('h', 0)] 



In [3]:
# 索引器
# loc and iloc
data = pd.Series(["a","b","c"], index = [2,4,6])
print(data)
print("\n",data.loc[2],"\n")
print("\n",data.loc[4],"\n")
print("\n",data.iloc[2],"\n")
print("\n",data.iloc[0],"\n")
print("\nloc will locate key.\niloc will locate index\n")

2    a
4    b
6    c
dtype: object

 a 


 b 


 c 


 a 


loc will locate key.
iloc will locate index



In [4]:
# DataFrame selection
area = pd.Series({'California': 423967, 'Texas': 695662, 
 'New York': 141297, 'Florida': 170312, 
 'Illinois': 149995}) 

pop = pd.Series({'California': 38332521, 'Texas': 26448193, 
 'New York': 19651127, 'Florida': 19552860, 
 'Illinois': 12882135}) 

data = pd.DataFrame({'area':area, 'pop':pop}) 

print(data)

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135


In [5]:
# see df as dictionary

print(data["area"])


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


In [6]:
# access as attributes

print(data.area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


In [9]:
# see it as matrix
data['density'] = data['pop'] / data['area'] # added the third column

print(data.values)

print("you can transpose the matrix\n")
print("\n",data.T,"\n") # transpose the matrix 

[[4.23967000e+05 3.83325210e+07 9.04139261e+01]
 [6.95662000e+05 2.64481930e+07 3.80187404e+01]
 [1.41297000e+05 1.96511270e+07 1.39076746e+02]
 [1.70312000e+05 1.95528600e+07 1.14806121e+02]
 [1.49995000e+05 1.28821350e+07 8.58837628e+01]]
you can transpose the matrix


            California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01 



In [10]:
# to access one row 
print(data.values[0])

[4.23967000e+05 3.83325210e+07 9.04139261e+01]


In [11]:
# to access one clomun
print(data["density"])

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64


In [18]:
# 使用index locator iloc

print(data.iloc[:2,:2]) # get 2 rows and 2 cllumns
print("\n",data.iloc[1:3,1:3],"\n")

              area       pop
California  423967  38332521
Texas       695662  26448193

                pop     density
Texas     26448193   38.018740
New York  19651127  139.076746 



In [28]:
print(data[1:3])
print("\n",data.loc[:,  [ "density","pop","area"]])

            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

                density       pop    area
California   90.413926  38332521  423967
Texas        38.018740  26448193  695662
New York    139.076746  19651127  141297
Florida     114.806121  19552860  170312
Illinois     85.883763  12882135  149995
