In [3]:
import numpy as np, pandas as pd
rng =np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
print(ser)

df = pd.DataFrame(rng.randint(1,11,(4,4)), columns=["A","B","V","T"])
print("\n",df)

0    6
1    3
2    7
3    4
dtype: int32

    A   B  V  T
0  7  10  3  7
1  8   5  4  8
2  8   3  6  5
3  2   8  6  2


In [7]:
print(np.exp2(ser))

print("\n\n",type(np.exp2(ser)))

0     64.0
1      8.0
2    128.0
3     16.0
dtype: float64


 <class 'pandas.core.series.Series'>


In [8]:
print(np.cos(df*np.pi/3))

     A    B    V    T
0  0.5 -0.5 -1.0  0.5
1 -0.5  0.5 -0.5 -0.5
2 -0.5 -1.0  1.0  0.5
3 -0.5 -0.5  1.0 -0.5


In [9]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 
 'California': 423967}, name='area') 
population = pd.Series({'California': 38332521, 'Texas': 26448193, 
 'New York': 19651127}, name='population')

print(population/area)

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64


In [10]:
df = pd.DataFrame({"area":area,"population":population})
print(df)

                 area  population
Alaska      1723337.0         NaN
California   423967.0  38332521.0
New York          NaN  19651127.0
Texas        695662.0  26448193.0


In [14]:
print(area.index.union(population.index))
print(area.index.intersection(population.index))
print(area.index.symmetric_difference(population.index))

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')
Index(['Texas', 'California'], dtype='object')
Index(['Alaska', 'New York'], dtype='object')


In [15]:
A = pd.Series([10086,10010,10000],index=["CMCC","CUCC","CTCC"])
print(A)

CMCC    10086
CUCC    10010
CTCC    10000
dtype: int64


In [16]:
B = pd.Series([10,20,30,40], index=["CMCC","CTCC","CUCC","CBCC"])
print(B)

CMCC    10
CTCC    20
CUCC    30
CBCC    40
dtype: int64


In [17]:
print(A + B)

CBCC        NaN
CMCC    10096.0
CTCC    10020.0
CUCC    10040.0
dtype: float64


In [18]:
print(B + A)

CBCC        NaN
CMCC    10096.0
CTCC    10020.0
CUCC    10040.0
dtype: float64


In [19]:
# 自定义缺失值
A.add(B, fill_value=693)

CBCC      733.0
CMCC    10096.0
CTCC    10020.0
CUCC    10040.0
dtype: float64

In [23]:
M1 = pd.DataFrame(rng.randint(1,10,(2,2)), columns = list("AB"))
print(M1)
print("\n","------------------------","\n")
M2 = pd.DataFrame(rng.randint(10,21,(3,4)), columns = list("BCEF"))
print(M2)
print("\n","------------------------","\n")
print(M1 + M2)

   A  B
0  4  6
1  2  2

 ------------------------ 

    B   C   E   F
0  19  13  17  16
1  18  17  14  11
2  14  17  19  18

 ------------------------ 

    A     B   C   E   F
0 NaN  25.0 NaN NaN NaN
1 NaN  20.0 NaN NaN NaN
2 NaN   NaN NaN NaN NaN


In [29]:
print(M1.stack().mean())
print(M1.add(M2, fill_value=M2.stack().mean()))

3.5
           A          B          C          E          F
0  20.083333  25.000000  29.083333  33.083333  32.083333
1  18.083333  20.000000  33.083333  30.083333  27.083333
2        NaN  30.083333  33.083333  35.083333  34.083333


In [33]:
# dataframe 与 series 运算

A= rng.randint(1,11,(5,4))
print(A)
print("\n","------------------------","\n")

print(A-A[0]) #matrix A minus first row for all other rows

[[ 5  6  4 10]
 [ 7  9  7  1]
 [ 1  9  9  4]
 [ 9  3  7  6]
 [ 8  9  5  1]]

 ------------------------ 

[[ 0  0  0  0]
 [ 2  3  3 -9]
 [-4  3  5 -6]
 [ 4 -3  3 -4]
 [ 3  3  1 -9]]


In [40]:
dfA = pd.DataFrame(A, columns=list("QRST"))
print(dfA)

print("\n----------------------------\n")
print(dfA-dfA.iloc[0])
print("\n----------------------------\n")


   Q  R  S   T
0  5  6  4  10
1  7  9  7   1
2  1  9  9   4
3  9  3  7   6
4  8  9  5   1

----------------------------

   Q  R  S  T
0  0  0  0  0
1  2  3  3 -9
2 -4  3  5 -6
3  4 -3  3 -4
4  3  3  1 -9

----------------------------



In [43]:
# if you want column subtract column 
dfA.subtract(dfA["S"], axis=0)

Q  R  S  T
0  1  2  0  6
1  0  2  0 -6
2 -8  0  0 -5
3  2 -4  0 -1
4  3  4  0 -4