In [12]:
import numpy as np
import torch

# create from numpy array with `torch.from_numpy()`

In [13]:
arr1 = np.random.randint(1,10,(3,3))

In [14]:
arr1

array([[8, 7, 7],
       [6, 2, 7],
       [6, 8, 4]])

In [15]:
x_data = torch.from_numpy(arr1)

In [16]:
x_data

tensor([[8, 7, 7],
        [6, 2, 7],
        [6, 8, 4]], dtype=torch.int32)

# create from raw data with `tourch.tensor()`

In [17]:
data = [[1,2,3],
       [4,5,6],
       [7,9,8]]

In [19]:
t1 = torch.tensor(data)

In [20]:
t1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 8]])

# create from other tensor with `torch.ones_like()`

In [23]:
t2 = torch.ones_like(t1)
t3 = torch.zeros_like(t2)
t4 = torch.rand_like(t1, dtype=torch.float)

In [24]:
t2

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [25]:
t3

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [26]:
t4

tensor([[0.9166, 0.4915, 0.8981],
        [0.9822, 0.8986, 0.0523],
        [0.1678, 0.6900, 0.4685]])

#  attributes of tensor shape, dtype, device

In [27]:
t4.shape

torch.Size([3, 3])

In [28]:
t4.dtype

torch.float32

In [29]:
t4.device

device(type='cpu')

# move to gpu is possible

In [46]:
if torch.cuda.is_available():
    t4 = t4.to("cuda")

In [47]:
t4.device

device(type='cpu')