In [6]:
import numpy as np

print(np.zeros(5))
print("\n")
print(np.zeros((3,4)))

[0. 0. 0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(np.ones(5))
print("\n")
print(np.ones((3,4,5)))

[1. 1. 1. 1. 1.]


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [8]:
print(np.full((3,3,3),9))

[[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]]


In [14]:
print(np.arange(5)) # from 0 to 5
print(np.arange(1,11)) # from 1 to 11
print(np.arange(1,21,5)) # from 1 to 21 step 5

[0 1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6 11 16]


In [17]:
print(np.linspace(1,3,6)) # linear space from 1 to 3, 6 numbers

[1.  1.4 1.8 2.2 2.6 3. ]


In [18]:
# random.random Only 1 gragument, shape of array

print(np.random.random((3,4)))

[[0.57783102 0.95874012 0.35593517 0.01722848]
 [0.465598   0.56175857 0.86376326 0.29027046]
 [0.27548575 0.15872714 0.67078668 0.93234724]]


In [21]:
# random.normal 3 args, mean, variabnce, shape
print(np.random.normal(0,1,(3,4))) 

[[ 1.26099182  0.19758963  1.5854798   0.29427   ]
 [-0.11770212 -0.65546641 -0.39462305  1.51672259]
 [ 0.18445484  0.17312162 -0.75187111 -1.25670681]]


In [30]:
# random.randint 3 args  min, max, shape
print(np.random.randint(80,100,(3,4)))

[[87 84 84 97]
 [93 84 82 88]
 [81 80 93 94]]
