In [2]:
# np array properties

import numpy as np
np.random.seed(0)
print("array1 ---------------------------------")
x1 = np.random.randint(10, size=6)
print(x1)
print("array2 ---------------------------------")
x2 = np.random.randint(10, size=(6,6))
print(x2)
print("array3 ---------------------------------")
x3 = np.random.randint(10, size=(6,6,6))
print(x3)

# ndim dimension, shape, and size 

print("the dimesnion of x3 is : " + str(x3.ndim) )
print("the shape of x3 is : " + str(x3.shape) )
print("the size of x3 is : " + str(x3.size) )

# also datatype
print("datetype of x3: ", x3.dtype)
print("itemsize of x3: ", x3.itemsize)
print("nbytes of x3: ", x3.nbytes)

array1 ---------------------------------
[5 0 3 3 7 9]
array2 ---------------------------------
[[3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]]
array3 ---------------------------------
[[[0 4 7 3 2 7]
  [2 0 0 4 5 5]
  [6 8 4 1 4 9]
  [8 1 1 7 9 9]
  [3 6 7 2 0 3]
  [5 9 4 4 6 4]]

 [[4 3 4 4 8 4]
  [3 7 5 5 0 1]
  [5 9 3 0 5 0]
  [1 2 4 2 0 3]
  [2 0 7 5 9 0]
  [2 7 2 9 2 3]]

 [[3 2 3 4 1 2]
  [9 1 4 6 8 2]
  [3 0 0 6 0 6]
  [3 3 8 8 8 2]
  [3 2 0 8 8 3]
  [8 2 8 4 3 0]]

 [[4 3 6 9 8 0]
  [8 5 9 0 9 6]
  [5 3 1 8 0 4]
  [9 6 5 7 8 8]
  [9 2 8 6 6 9]
  [1 6 8 8 3 2]]

 [[3 6 3 6 5 7]
  [0 8 4 6 5 8]
  [2 3 9 7 5 3]
  [4 5 3 3 7 9]
  [9 9 7 3 2 3]
  [9 7 7 5 1 2]]

 [[2 8 1 5 8 4]
  [0 2 5 5 0 8]
  [1 1 0 3 8 8]
  [4 4 0 9 3 7]
  [3 2 1 1 2 1]
  [4 2 5 5 5 2]]]
the dimesnion of x3 is : 3
the shape of x3 is : (6, 6, 6)
the size of x3 is : 216
datetype of x3:  int32
itemsize of x3:  4
nbytes of x3:  864


In [13]:
# slice the array
x = np.arange(10) #create array from 0 bis 9
print(x)
print(x[:5])
print(x[5:])
print(x[3:5]) # 左边不包括，右边包括
print(x[::2])# 每隔一个
print(x[1::2])# 从索引1开始每隔两
print(x[::-1])# 倒数
print(x[6::-2])# 从6开始倒数每隔2

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 4]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[6 4 2 0]


In [22]:
# slice multi-dimension array
print(x2)
print("-------------")
print(x2[:2,:3])# 前两row, 前三col
print("-------------")
print(x2[:,::2]) # all row, every 2 col
print("-------------")
print(x2[4::-2,:]) # from index4 row reverse every2 row, all col

[[3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]]
-------------
[[3 5 2]
 [8 8 1]]
-------------
[[3 2 7]
 [8 1 7]
 [8 5 8]
 [4 0 5]
 [2 8 3]
 [3 0 9]]
-------------
[[2 3 8 1 3 3]
 [8 1 5 9 8 9]
 [3 5 2 4 7 6]]
