In [1]:
#Python list is not just a list
list1 = [1,2,3,4,5]
print(type(list1))
print(type(list1[1]))



<class 'list'>
<class 'int'>


In [2]:
# craete a string list
str_list = [str(i) for i in list1]
print(type(str_list))
print(type(str_list[0]))

<class 'list'>
<class 'str'>


In [3]:
# use numpy create array
import numpy as np

ar1 = np.array([1,2,3,4,5])

print(ar1)

for i in ar1:
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [4]:
# create zeros array
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# create ones array

np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# create full float array

np.full((10,10), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# create with arange step

np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# crate betwen 1 and 10 
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
# create random matrix
np.random.random((3,5))

array([[0.17332012, 0.11116923, 0.87443295, 0.59367956, 0.97048435],
       [0.97748953, 0.14757254, 0.87688794, 0.64022392, 0.34043168],
       [0.93617642, 0.72887088, 0.2107513 , 0.82368749, 0.27983848]])

In [21]:
# create random but normal distribution

np.random.normal(0,1,(5,5)) # 5by5 mean 0 sd 1

array([[-0.82469029, -1.05235372, -1.96293313,  0.22429749, -1.23579121],
       [ 1.48915519,  1.60978157, -0.39534804, -1.84395571, -0.12209078],
       [ 0.67967288, -0.88964647,  0.26559705,  0.92722025, -0.1723165 ],
       [-0.28812412,  2.76086384,  1.33210189,  1.20126772, -2.59313201],
       [-0.50439616, -1.73126868,  0.20691465, -1.11833013,  0.65375004]])

In [22]:
# random int matrix

np.random.randint(1,10, (5,5))

array([[6, 6, 2, 6, 8],
       [5, 7, 5, 8, 6],
       [8, 5, 8, 6, 8],
       [7, 6, 9, 1, 6],
       [1, 1, 1, 5, 3]])

In [23]:
# create identity matrix with eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# create array from radom values from computer memory
np.empty(3)

array([9.56166408e-312, 0.00000000e+000, 1.89146896e-307])

In [37]:
# nesting array

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Dimension 2")
print("--------------------------------------------")
a1 = np.array([a,b,c])
print(a1)
print("--------------------------------------------")
a2 = np.array([b,c,a])
print(a2)
print("--------------------------------------------")
a3 = np.array([c,a,b])
print(a3)
print("--------------------------------------------")
print("Dimension 3")
A1 = np.array([a1,a2,a3])
print(A1)
print("--------------------------------------------")

A2 = np.array([a2,a3, a1])
print(A2)
print("--------------------------------------------")

A3 = np.array([a3,a1,a2])
print(A3)
print("--------------------------------------------")
print("Dimension 4")
D1 = np.array([A1, A2, A3])
print(D1)
print("--------------------------------------------")

D2 = np.array([ A2, A3,A1])
print(D2)
print("--------------------------------------------")

D3 = np.array([ A3,A1, A2])
print(D3)
print("--------------------------------------------")
print("Dimension 5")
fiveDim = np.array([D1,D3,D2])
print(fiveDim)

print("----------------------------------------------")

Dimension 2
--------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------
[[4 5 6]
 [7 8 9]
 [1 2 3]]
--------------------------------------------
[[7 8 9]
 [1 2 3]
 [4 5 6]]
--------------------------------------------
Dimension 3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 5 6]
  [7 8 9]
  [1 2 3]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]]]
--------------------------------------------
[[[4 5 6]
  [7 8 9]
  [1 2 3]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
--------------------------------------------
[[[7 8 9]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 5 6]
  [7 8 9]
  [1 2 3]]]
--------------------------------------------
Dimension 4
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[4 5 6]
   [7 8 9]
   [1 2 3]]

  [[7 8 9]
   [1 2 3]
   [4 5 6]]]


 [[[4 5 6]
   [7 8 9]
   [1 2 3]]

  [[7 8 9]
   [1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[7 8 9]
   [1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]
   [7 